### ISSUE TITLE
Shield not working?

### ISSUE THREAD

**Issue by r3m4k3** [sparkfun/ESP8266_WiFi_Shield#7]
Hi there,

I have wired Arduino Mega 2560 with your shield.
I have uploaded demo code and it returns me false in line eso8266.begin(), what does it mean?
Does it mean, that the hardware is corrupt?
Then, how can I get information, what is precisely broken?
Can I check for example voltage or something for pins and then know or hardware is down, or maybe I had bad soldered the goldpins, or there is a short circuit.

Thanks, best regards

**Comment by bboyho** [comment]
Hi,

I was checking something in the GitHub repository and noticed this issue filed. 

### Software Serial Pins

The ESP8266 Shield was designed to stack on the Arduino Uno footprint with the ATmega328P microcontroller. Not all pins on the Arduino Mega 2560 support change interrupts for Rx so software serial will not work on pin 8. Check out this note from Arduino.cc on the Software Serial Library =>  [https://www.arduino.cc/en/Reference/softwareSerial](https://www.arduino.cc/en/Reference/softwareSerial) ]. You can probably get it working on the Arduino Mega 2560 by [redefining the library on pin 8](https://github.com/sparkfun/SparkFun_ESP8266_AT_Arduino_Library/blob/master/src/SparkFunESP8266WiFi.h#L34) to:

    #define ESP8266_SW_TX	10

You will also need to reroute the pin so that the ESP8266's Tx pin connects pin 10.

### Solder Joints 

Just like any basic troubleshooting, you should also [check your solder joints](https://learn.sparkfun.com/tutorials/sparkfun-troubleshooting-tips#bad-solder-joints). However, I do not believe this is the issue.
